[Directories]
CWD = 'E:\Documents (E)\neovim\photoReset'
Destination = 'BLANK'

[Metadata]
Date = '2026-02-13'
Exposure = 'BLANK'
LensModel = 'BLANK'
Location = 'BLANK'
Orientation = 'BLANK'
Parameters = false

[Parameter]
Metering = 'Matrix'
MeteringOptions = [ 'Spot', 'Center-weighted', 'Matrix', 'Evaluative' ]

[Sorting]
ByCameraModel = false
ByDate = true
ByFormat = false
ByOtherMeta = false

[System]
OS = 'Windows'

[[Camera]]
CameraBrand = 'Sony'
CameraModel = 'A7CIII'
Formats = [ '.ARW' ]