[System]
OS = 

[Directories]
DefaultCWD =
DefaultDestination = 

[Sorting]
ByDate = true
ByFormat = false
ByCameraModel = false
ByOtherMeta = false     #direct to other specific metadata

#TODO: method to pull metadata from detected files to insert into the table below
[Metadata]  #multiple options can be organized once `ByOtherMeta` is true
LensModel = 
ExposureLevel = 
Location = 
Orientation = 
Parameter = false   #GO TO [Parameter] table

[Parameter]
Metering = Matrix
MeteringOptions = ["Spot", "Center-weighted", "Matrix", "Evaluative"]

[[Cameras]]	#Camera specific metadata settings
CameraBrand = 
CameraModel = 
RAWFormat = 

